mylibber_backend:
    resource: "@MylibberBackendBundle/Resources/config/routing.yml"
    prefix:   /

mylibber_mylib:
    resource: "@MylibberMylibBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
