parameters:
#    mylibber_backend.example.class: Mylibber\BackendBundle\Example

services:
#    mylibber_backend.example:
#        class: %mylibber_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
