parameters:
#    mylibber_mylib.example.class: Mylibber\MylibBundle\Example

services:
#    mylibber_mylib.example:
#        class: %mylibber_mylib.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
