<?php

namespace Mylibber\BackendBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Mylibber\BackendBundle\Controller\UserController();
        return $instance;
    }
}
